#hash((entire . #hash((adminname . "^1Blue^4Red")
                      (adminstart . #f)
                      (allowlatejoin . #t)
                      (antilag . #t)
                      (antilagforgiving . #f)
                      (antilagonly . #f)
                      (bot_enable . #t)
                      (campaign . "campaign_africa")
                      (campaigninfo . #"2 2")
                      (disableglobalchat . #f)
                      (disablevoting . #f)
                      (email . "the-incredible-jesus@gmx.net")
                      (gamename . "baseETQW-1")
                      (gamereviewreadywait . #f)
                      (irc . "sorry none")
                      (map . "maps/island")
                      (maxplayers . 24)
                      (minplayers . 2)
                      (motd . ("^2.^1\\^>JESUS^1/^2.^0 - The one and only!"
                               "Teamplayers are welcome!"
                               "^0Server: ^2Intel Core I7, 3.4Ghz"
                               "^0TS3: ^15.9.88.23:9987"))
                      (name . "^2.^1\\^7JESUS^1/^2.^7 - ^4UnRanked")
                      (needpass . #f)
                      (noproficiency . #f)
                      (privateclients . #f)
                      (pure . #t)
                      (readypercent . 51)
                      (rules . "sdGameRulesCampaign")
                      (serverdedicated . #t)
                      (serverpunkbusterenabled . #f)
                      (spectators . #t)
                      (teamdamage . #t)
                      (teamforcebalance . #t)
                      (timelimit . 20.0)
                      (version . "ETQW 1.5.12663.12663  linux-x86 May  9 2008 13:47:37")
                      (website . "http://www.jesus-clan.com")
                      (osmask . 7)
                      (ranked . #f)
                      (timeleft . 615966) ; 0x24 0x66 0x09 0x00
                      (gamestate . in-progress)
                      (servertype . regular)
                      (interested-clients . 0)
                      (players . #hash((0 . #hash((bot . #f)
                                                  (clantag . #f)
                                                  (clantag_pos . 0)
                                                  (deaths . 6)
                                                  (id . 0)
                                                  (kills . 10)
                                                  (name . "^[Joe_Blob")
                                                  (ping . 44)
                                                  (team . "strogg")
                                                  (xp . 34.59995651245117)))
                                       (1 . #hash((bot . #f)
                                                  (clantag . #f)
                                                  (clantag_pos . 0)
                                                  (deaths . 3)
                                                  (id . 1)
                                                  (kills . 0)
                                                  (name . "WoDaN")
                                                  (ping . 18)
                                                  (team . "strogg")
                                                  (xp . 11.522493362426758)))
                                       (2 . #hash((bot . #f)
                                                  (clantag . #f)
                                                  (clantag_pos . 0)
                                                  (deaths . 0)
                                                  (id . 2)
                                                  (kills . 0)
                                                  (name . "^eKrish")
                                                  (ping . 55)
                                                  (team . #f)
                                                  (xp . 201.9859619140625)))
                                       (3 . #hash((bot . #f)
                                                  (clantag . #f)
                                                  (clantag_pos . 0)
                                                  (deaths . 0)
                                                  (id . 3)
                                                  (kills . 0)
                                                  (name . "Norse.")
                                                  (ping . 115)
                                                  (team . #f)
                                                  (xp . 0.0)))
                                       (4 . #hash((bot . #f)
                                                  (clantag . #f)
                                                  (clantag_pos . 1)
                                                  (deaths . 6)
                                                  (id . 4)
                                                  (kills . 7)
                                                  (name . "^1theonething")
                                                  (ping . 67)
                                                  (team . "gdf")
                                                  (xp . 101.09241485595703)))
                                       (18 . #hash((bot . #f)
                                                   (clantag . "^7a^;im^1b^;ot^0")
                                                   (clantag_pos . 0)
                                                   (deaths . 4)
                                                   (id . 18)
                                                   (kills . 2)
                                                   (name . "^1.^;e^7x^;e")
                                                   (ping . 90)
                                                   (team . "gdf")
                                                   (xp . 96.97867584228516)))))))
      (server-info . #hash((adminname . "^1Blue^4Red")
                           (adminstart . #f)
                           (allowlatejoin . #t)
                           (antilag . #t)
                           (antilagforgiving . #f)
                           (antilagonly . #f)
                           (bot_enable . #t)
                           (campaign . "campaign_africa")
                           (campaigninfo . #"2 2")
                           (disableglobalchat . #f)
                           (disablevoting . #f)
                           (email . "the-incredible-jesus@gmx.net")
                           (gamename . "baseETQW-1")
                           (gamereviewreadywait . #f)
                           (irc . "sorry none")
                           (map . "maps/island")
                           (maxplayers . 24)
                           (minplayers . 2)
                           (motd . ("^2.^1\\^>JESUS^1/^2.^0 - The one and only!"
                                    "Teamplayers are welcome!"
                                    "^0Server: ^2Intel Core I7, 3.4Ghz"
                                    "^0TS3: ^15.9.88.23:9987"))
                           (name . "^2.^1\\^7JESUS^1/^2.^7 - ^4UnRanked")
                           (needpass . #f)
                           (noproficiency . #f)
                           (privateclients . #f)
                           (pure . #t)
                           (readypercent . 51)
                           (rules . "sdGameRulesCampaign")
                           (serverdedicated . #t)
                           (serverpunkbusterenabled . #f)
                           (spectators . #t)
                           (teamdamage . #t)
                           (teamforcebalance . #t)
                           (timelimit . 20.0)
                           (version . "ETQW 1.5.12663.12663  linux-x86 May  9 2008 13:47:37")
                           (website . "http://www.jesus-clan.com")))
      (fixed-server-info . #hash((osmask . 7)
                                 (ranked . #f)
                                 (timeleft . 615966) ; 0x24 0x66 0x09 0x00
                                 (gamestate . in-progress)
                                 (servertype . regular)
                                 (interested-clients . 0)))
      (first-player . #hash((id . 0)
                            (ping . 44)
                            (name . "^[Joe_Blob")
                            (clantag_pos . 0)
                            (clantag . #f)
                            (bot . #f)))
      (first-player-extra . #hash((id . 0)
                                  (xp . 34.59995651245117)
                                  (team . "strogg")
                                  (kills . 10)
                                  (deaths . 6))))
